<?php

/**
 * This is the model base class for the table "categoria".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Categoria".
 *
 * Columns in table "categoria" available as properties of the model,
 * followed by relations of table "categoria" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $peso
 * @property string $estado
 * @property integer $max_entidad
 * @property integer $max_foto
 *
 * @property Entidad[] $entidads
 */
abstract class BaseCategoria extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'categoria';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre, estado, max_entidad, max_foto', 'required'),
            array('peso, max_entidad, max_foto', 'numerical', 'integerOnly'=>true),
            array('nombre', 'length', 'max'=>45),
            array('estado', 'length', 'max'=>8),
            array('estado', 'in', 'range' => array('ACTIVO','INACTIVO')), // enum,
            array('peso', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, nombre, peso, estado, max_entidad, max_foto', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'entidads' => array(self::HAS_MANY, 'Entidad', 'categoria_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'peso' => Yii::t('app', 'Peso'),
                'estado' => Yii::t('app', 'Estado'),
                'max_entidad' => Yii::t('app', 'Max Entidad'),
                'max_foto' => Yii::t('app', 'Max Foto'),
                'entidads' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('peso', $this->peso);
        $criteria->compare('estado', $this->estado, true);
        $criteria->compare('max_entidad', $this->max_entidad);
        $criteria->compare('max_foto', $this->max_foto);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}