<?php

/**
 * This is the model base class for the table "entidad_foto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EntidadFoto".
 *
 * Columns in table "entidad_foto" available as properties of the model,
 * followed by relations of table "entidad_foto" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $ruta
 * @property integer $entidad_id
 *
 * @property Entidad $entidad
 */
abstract class BaseEntidadFoto extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'entidad_foto';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre, ruta, entidad_id', 'required'),
            array('entidad_id', 'numerical', 'integerOnly'=>true),
            array('nombre', 'length', 'max'=>256),
            array('ruta', 'length', 'max'=>512),
            array('id, nombre, ruta, entidad_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'entidad' => array(self::BELONGS_TO, 'Entidad', 'entidad_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'ruta' => Yii::t('app', 'Ruta'),
                'entidad_id' => Yii::t('app', 'Entidad'),
                'entidad' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('ruta', $this->ruta, true);
        $criteria->compare('entidad_id', $this->entidad_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}