<?php

/**
 * This is the model base class for the table "producto_subcategoria".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProductoSubcategoria".
 *
 * Columns in table "producto_subcategoria" available as properties of the model,
 * followed by relations of table "producto_subcategoria" available as properties of the model.
 *
 * @property integer $id
 * @property integer $categoria_producto_id
 * @property string $nombre
 * @property string $descripcion
 * @property string $estado
 *
 * @property Producto[] $productos
 * @property ProductoCategoria $categoriaProducto
 */
abstract class BaseProductoSubcategoria extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'producto_subcategoria';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('categoria_producto_id, nombre', 'required'),
            array('categoria_producto_id', 'numerical', 'integerOnly'=>true),
            array('nombre', 'length', 'max'=>45),
            array('estado', 'length', 'max'=>8),
            array('descripcion', 'safe'),
            array('estado', 'in', 'range' => array('ACTIVO','INACTIVO')), // enum,
            array('descripcion, estado', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, categoria_producto_id, nombre, descripcion, estado', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'productos' => array(self::HAS_MANY, 'Producto', 'subcategoria_producto_id'),
            'categoriaProducto' => array(self::BELONGS_TO, 'ProductoCategoria', 'categoria_producto_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'categoria_producto_id' => Yii::t('app', 'Categoria Producto'),
                'nombre' => Yii::t('app', 'Nombre'),
                'descripcion' => Yii::t('app', 'Descripcion'),
                'estado' => Yii::t('app', 'Estado'),
                'productos' => null,
                'categoriaProducto' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('categoria_producto_id', $this->categoria_producto_id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('descripcion', $this->descripcion, true);
        $criteria->compare('estado', $this->estado, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}