<?php

/**
 * This is the model base class for the table "item_foto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ItemFoto".
 *
 * Columns in table "item_foto" available as properties of the model,
 * followed by relations of table "item_foto" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $ruta
 * @property integer $item_id
 *
 * @property Item $item
 */
abstract class BaseItemFoto extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'item_foto';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('id, nombre, ruta, item_id', 'required'),
            array('id, item_id', 'numerical', 'integerOnly'=>true),
            array('nombre', 'length', 'max'=>64),
            array('ruta', 'length', 'max'=>124),
            array('id, nombre, ruta, item_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'item' => array(self::BELONGS_TO, 'Item', 'item_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'ruta' => Yii::t('app', 'Ruta'),
                'item_id' => Yii::t('app', 'Item'),
                'item' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('ruta', $this->ruta, true);
        $criteria->compare('item_id', $this->item_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}