<?php

/**
 * This is the model base class for the table "provincia".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Provincia".
 *
 * Columns in table "provincia" available as properties of the model,
 * followed by relations of table "provincia" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $pais_id
 *
 * @property Ciudad[] $ciudads
 * @property Pais $pais
 */
abstract class BaseProvincia extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'provincia';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre, pais_id', 'required'),
            array('pais_id', 'numerical', 'integerOnly'=>true),
            array('nombre', 'length', 'max'=>45),
            array('id, nombre, pais_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'ciudads' => array(self::HAS_MANY, 'Ciudad', 'provincia_id'),
            'pais' => array(self::BELONGS_TO, 'Pais', 'pais_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'pais_id' => Yii::t('app', 'Pais'),
                'ciudads' => null,
                'pais' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('pais_id', $this->pais_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}