<?php

/**
 * This is the model base class for the table "evento_prioridad".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EventoPrioridad".
 *
 * Columns in table "evento_prioridad" available as properties of the model,
 * followed by relations of table "evento_prioridad" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $color
 *
 * @property Evento[] $eventos
 */
abstract class BaseEventoPrioridad extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'evento_prioridad';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre', 'required'),
            array('nombre', 'length', 'max'=>64),
            array('color', 'length', 'max'=>10),
            array('color', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, nombre, color', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'eventos' => array(self::HAS_MANY, 'Evento', 'evento_prioridad_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'color' => Yii::t('app', 'Color'),
                'eventos' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('color', $this->color, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}