-- MySQL Script generated by MySQL Workbench
-- 09/11/14 21:19:00
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cvirtual
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cvirtual` DEFAULT CHARACTER SET latin1 ;
USE `cvirtual` ;

-- -----------------------------------------------------
-- Table `cvirtual`.`cruge_authitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvirtual`.`cruge_authitem` (
  `name` VARCHAR(64) NOT NULL,
  `type` INT(11) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `bizrule` TEXT NULL DEFAULT NULL,
  `data` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cvirtual`.`cruge_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvirtual`.`cruge_user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `regdate` BIGINT(30) NULL DEFAULT NULL,
  `actdate` BIGINT(30) NULL DEFAULT NULL,
  `logondate` BIGINT(30) NULL DEFAULT NULL,
  `username` VARCHAR(64) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(64) NULL DEFAULT NULL COMMENT 'Hashed password',
  `authkey` VARCHAR(100) NULL DEFAULT NULL COMMENT 'llave de autentificacion',
  `state` INT(11) NULL DEFAULT '0',
  `totalsessioncounter` INT(11) NULL DEFAULT '0',
  `currentsessioncounter` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cvirtual`.`cruge_authassignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvirtual`.`cruge_authassignment` (
  `userid` INT(11) NOT NULL,
  `bizrule` TEXT NULL DEFAULT NULL,
  `data` TEXT NULL DEFAULT NULL,
  `itemname` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`userid`, `itemname`),
  INDEX `fk_cruge_authassignment_cruge_authitem1` (`itemname` ASC),
  INDEX `fk_cruge_authassignment_user` (`userid` ASC),
  CONSTRAINT `fk_cruge_authassignment_cruge_authitem1`
    FOREIGN KEY (`itemname`)
    REFERENCES `cvirtual`.`cruge_authitem` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cruge_authassignment_user`
    FOREIGN KEY (`userid`)
    REFERENCES `cvirtual`.`cruge_user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cvirtual`.`cruge_authitemchild`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvirtual`.`cruge_authitemchild` (
  `parent` VARCHAR(64) NOT NULL,
  `child` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`parent`, `child`),
  INDEX `child` (`child` ASC),
  CONSTRAINT `crugeauthitemchild_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `cvirtual`.`cruge_authitem` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `crugeauthitemchild_ibfk_2`
    FOREIGN KEY (`child`)
    REFERENCES `cvirtual`.`cruge_authitem` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cvirtual`.`cruge_field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvirtual`.`cruge_field` (
  `idfield` INT(11) NOT NULL AUTO_INCREMENT,
  `fieldname` VARCHAR(20) NOT NULL,
  `longname` VARCHAR(50) NULL DEFAULT NULL,
  `position` INT(11) NULL DEFAULT '0',
  `required` INT(11) NULL DEFAULT '0',
  `fieldtype` INT(11) NULL DEFAULT '0',
  `fieldsize` INT(11) NULL DEFAULT '20',
  `maxlength` INT(11) NULL DEFAULT '45',
  `showinreports` INT(11) NULL DEFAULT '0',
  `useregexp` VARCHAR(512) NULL DEFAULT NULL,
  `useregexpmsg` VARCHAR(512) NULL DEFAULT NULL,
  `predetvalue` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idfield`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cvirtual`.`cruge_fieldvalue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvirtual`.`cruge_fieldvalue` (
  `idfieldvalue` INT(11) NOT NULL AUTO_INCREMENT,
  `iduser` INT(11) NOT NULL,
  `idfield` INT(11) NOT NULL,
  `value` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idfieldvalue`),
  INDEX `fk_cruge_fieldvalue_cruge_user1` (`iduser` ASC),
  INDEX `fk_cruge_fieldvalue_cruge_field1` (`idfield` ASC),
  CONSTRAINT `fk_cruge_fieldvalue_cruge_field1`
    FOREIGN KEY (`idfield`)
    REFERENCES `cvirtual`.`cruge_field` (`idfield`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cruge_fieldvalue_cruge_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `cvirtual`.`cruge_user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cvirtual`.`cruge_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvirtual`.`cruge_session` (
  `idsession` INT(11) NOT NULL AUTO_INCREMENT,
  `iduser` INT(11) NOT NULL,
  `created` BIGINT(30) NULL DEFAULT NULL,
  `expire` BIGINT(30) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT '0',
  `ipaddress` VARCHAR(45) NULL DEFAULT NULL,
  `usagecount` INT(11) NULL DEFAULT '0',
  `lastusage` BIGINT(30) NULL DEFAULT NULL,
  `logoutdate` BIGINT(30) NULL DEFAULT NULL,
  `ipaddressout` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idsession`),
  INDEX `crugesession_iduser` (`iduser` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cvirtual`.`cruge_system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvirtual`.`cruge_system` (
  `idsystem` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `largename` VARCHAR(45) NULL DEFAULT NULL,
  `sessionmaxdurationmins` INT(11) NULL DEFAULT '30',
  `sessionmaxsameipconnections` INT(11) NULL DEFAULT '10',
  `sessionreusesessions` INT(11) NULL DEFAULT '1' COMMENT '1yes 0no',
  `sessionmaxsessionsperday` INT(11) NULL DEFAULT '-1',
  `sessionmaxsessionsperuser` INT(11) NULL DEFAULT '-1',
  `systemnonewsessions` INT(11) NULL DEFAULT '0' COMMENT '1yes 0no',
  `systemdown` INT(11) NULL DEFAULT '0',
  `registerusingcaptcha` INT(11) NULL DEFAULT '0',
  `registerusingterms` INT(11) NULL DEFAULT '0',
  `terms` BLOB NULL DEFAULT NULL,
  `registerusingactivation` INT(11) NULL DEFAULT '1',
  `defaultroleforregistration` VARCHAR(64) NULL DEFAULT NULL,
  `registerusingtermslabel` VARCHAR(100) NULL DEFAULT NULL,
  `registrationonlogin` INT(11) NULL DEFAULT '1',
  PRIMARY KEY (`idsystem`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cvirtual`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvirtual`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `peso` INT NULL,
  `estado` ENUM('ACTIVO','INACTIVO') NOT NULL,
  `max_entidad` INT NOT NULL,
  `max_foto` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvirtual`.`industria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvirtual`.`industria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` ENUM('ACTIVO','INACTIVO') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvirtual`.`entidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvirtual`.`entidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(64) NOT NULL,
  `razon_social` VARCHAR(64) NULL,
  `documento` VARCHAR(20) NULL,
  `website` VARCHAR(45) NULL,
  `raking` INT NULL,
  `telefono` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `max_entidad` INT NULL,
  `estado` ENUM('ACTIVO','INACTIVO') NOT NULL,
  `matriz` TINYINT NULL,
  `categoria_id` INT NULL,
  `industria_id` INT NULL,
  `entidad_id` INT NULL,
  `max_foto` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_entidad_categoria1_idx` (`categoria_id` ASC),
  INDEX `fk_entidad_industria1_idx` (`industria_id` ASC),
  INDEX `fk_entidad_entidad1_idx` (`entidad_id` ASC),
  CONSTRAINT `fk_entidad_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `cvirtual`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entidad_industria1`
    FOREIGN KEY (`industria_id`)
    REFERENCES `cvirtual`.`industria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entidad_entidad1`
    FOREIGN KEY (`entidad_id`)
    REFERENCES `cvirtual`.`entidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvirtual`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvirtual`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvirtual`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvirtual`.`provincia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_provincia_pais1_idx` (`pais_id` ASC),
  CONSTRAINT `fk_provincia_pais1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `cvirtual`.`pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvirtual`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvirtual`.`ciudad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `provincia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ciudad_provincia1_idx` (`provincia_id` ASC),
  CONSTRAINT `fk_ciudad_provincia1`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `cvirtual`.`provincia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvirtual`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvirtual`.`direccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `calle_principal` VARCHAR(64) NULL,
  `calle_secundaria` VARCHAR(64) NULL,
  `numero` VARCHAR(20) NULL,
  `ciudad_id` INT NULL,
  `provincia_id` INT NULL,
  `pais_id` INT NULL,
  `coord_x` DOUBLE NULL,
  `coord_y` DOUBLE NULL,
  `referencia` VARCHAR(45) NULL,
  `entidad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_direccion_ciudad1_idx` (`ciudad_id` ASC),
  CONSTRAINT `fk_direccion_ciudad1`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `cvirtual`.`ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvirtual`.`entidad_foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvirtual`.`entidad_foto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(256) NOT NULL,
  `ruta` VARCHAR(512) NOT NULL,
  `entidad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_entidad_foto_entidad1_idx` (`entidad_id` ASC),
  CONSTRAINT `fk_entidad_foto_entidad1`
    FOREIGN KEY (`entidad_id`)
    REFERENCES `cvirtual`.`entidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
